# SciPy

SciPy ist eine Sammlung von mathematischen Algorithmen und weiteren üblichen Funktionen der Mathematik. Aufgebaut ist es auf der NumPy Erweiterung, die wir bereits kennen. SciPy ergänzt Python um wirklich mächtige Kommandos zur Datananalyse und Visualisierung. Mit SciPy wird eine interaktive Python Sitzung ermöglicht, deren Datenverarbeitung und System-Prototyping-Umgebung mit denen von MATLAB, IDL, Octave, R-Lab und SciLab konkurrieren kann.

Der zusätzliche Nutzen davon SciPy auf Python aufzubauen liegt darin, eine mächtige Programmiersprache zur Verfügung zu haben, um anspruchsvolle Programme und spezielle Anwendungen zu entwickeln. Wissenschaftliche Anwendungen, die SciPy nutzen, profitieren von der Entwicklung zusätzlicher Module in einer Vielzahl an Nischen der Software-Entwicklung durch Entwickler aus der ganzen Welt.

Alles von der parallelen Programmierung bis zu Web- und Datensubroutinen oder Klassen steht dem Python Programmierer zur Verfügung. All diese wertvollen Tools stehen einem zusätzlich zur mathematischen Library von SciPy zur Verfügung. 

Wir werden insgesamt mehr Fokus auf NumPy Arrays legen und schauen uns deshalb einige der SciPy Möglichkeiten exemplarisch an:

In [1]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,8]])

## Lineare Algebra

`linalg`

In [2]:
from scipy import linalg

Determinant einer Matrix

In [3]:
linalg.det(A)

2.999999999999997

Die LU-Zerlegung einer Matrix berechnen.

Die Zerlegung lautet:

    A = P L U
    
wobei P die Permutationsmatrix, L die linke untere und R die rechte obere Matrix ist.

In [4]:
P, L, U = linalg.lu(A)

In [5]:
P

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]])

In [6]:
L

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.14285714,  1.        ,  0.        ],
       [ 0.57142857,  0.5       ,  1.        ]])

In [7]:
U

array([[ 7.        ,  8.        ,  8.        ],
       [ 0.        ,  0.85714286,  1.85714286],
       [ 0.        ,  0.        ,  0.5       ]])

In [8]:
np.dot(L,U)

array([[ 7.,  8.,  8.],
       [ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

Wir können außerdem Eigenvalues und Eigenvektor der Matrix herausfinden:

In [9]:
EW, EV = linalg.eig(A)

In [10]:
EW

array([ 15.55528261+0.j,  -1.41940876+0.j,  -0.13587385+0.j])

In [11]:
EV

array([[-0.24043423, -0.67468642,  0.51853459],
       [-0.54694322, -0.23391616, -0.78895962],
       [-0.80190056,  0.70005819,  0.32964312]])

Und das Lösen von linearen Gleichungen ist ebenfalls möglich:

In [13]:
v = np.array([[2],[3],[5]])

In [14]:
v

array([[2],
       [3],
       [5]])

In [15]:
s = linalg.solve(A,v)

In [16]:
s

array([[-2.33333333],
       [ 3.66666667],
       [-1.        ]])

## Schwachbesetze Lineare Algebra

SciPy bietet einige Routinen um mit schwachbesetzten (en. sparse) und potentiell sehr großen Matrizen zu rechnen. Die notwendigen Tools sind im Untermodul `scipy.sparse`.

Wir können uns ein Beispiel anschauen, wie man eine große Matrix erstellt:

In [17]:
from scipy import sparse

In [18]:
A = sparse.lil_matrix((1000,1000))

In [19]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>

In [20]:
A[0,:100] = np.random.rand(100)

In [21]:
A[1,100:200] = A[0,:100]

In [22]:
A.setdiag(np.random.rand(1000))

In [23]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in LInked List format>

Lineare Algebra für schwachbesetzte Matrizen

In [24]:
from scipy.sparse import linalg

In [25]:
# Die Matix in das "Compressed Sparse Row Format" umwandeln
A.tocsr()

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in Compressed Sparse Row format>

In [26]:
A = A.tocsr()

In [27]:
b = np.random.rand(1000)

In [28]:
linalg.spsolve(A, b)

array([  8.90401804e+02,  -4.13531440e+02,   3.04147626e+00,
         5.47779778e-01,   5.55971026e-01,   1.48957019e+00,
         8.34958397e-01,   5.16301662e-01,   3.61651171e-01,
         1.42587167e-01,   3.01216401e+00,   3.05345216e+00,
         5.22168867e+00,   1.20479864e+00,   3.61782304e-01,
         1.56673315e+00,   8.16965546e-02,   4.57700100e-01,
         2.60843003e+00,   1.59000652e+00,   9.86173228e-01,
         2.71095195e+00,   4.84951886e-01,   7.26039668e-01,
         1.04108310e-01,   5.93915544e-01,   1.50945347e+00,
         4.07143689e-02,   2.72118983e-01,   1.05428342e+00,
         1.28991382e+00,   1.37195504e+00,   6.56289222e+00,
         5.84293219e-01,   1.31732812e+00,   1.02571897e-01,
         7.51086535e-01,   1.62748933e+01,   3.46592064e-01,
         6.62054446e-01,   2.35426095e+00,   2.69486058e-01,
         3.55383173e-01,   7.10427899e-01,   3.33537392e-01,
         1.46128162e+00,   8.93902251e-01,   2.79220440e-01,
         2.78466028e-01,

Darüber hinaus gibt es vieles mehr, wozu SciPy fähig ist. Beispiele sind Fourier-Transformationen oder die Besselsche Differentialgleichung. 

Für weitere Informationen schaut euch die [Dokumentation](https://docs.scipy.org/doc/scipy/reference/) an.

# Gut gemacht!