<a href="https://datamics.com/de/courses/"><img src=../../DATA/bg_datamics_top.png></a>

<em text-align:center>© Datamics</em>
# NumPy

NumPy (oder Numpy) ist eine Lineare Algebra Library für Python. Dass sie so wichtig für Data Science mit Python ist, liegt daran, dass fast alle Libraries im PyData Ökosystem auf NumPy zurückgreifen.

NumPy ist außerdem extrem schnell, da es Anbindung an die C Library hat. Für mehr Informationen darüber, warum man Arrays statt Listen verwenden sollte, könnt ihr diesen tollen [StackOverflow Post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists) lesen.

Wir werden nur die Grundlagen von NumPy lernen und es installieren, um damit arbeiten zu können.

## Installationsanleitung

**Ich empfehle ausdrücklich Python durch Verwendung der Anaconda Distribution zu installieren. So können wir sicher sein, dass alle zugrundeliegenden Notwendigkeiten (wie z.B. Lineare Algebara Libraries) installiert sind. Wenn ihr Anaconda nutzt, dann installiert NumPy, indem ihr zu eurem Terminal oder der Kommandozeile geht und eingebt:**

    conda install numpy
    
**Wenn du kein Anaconda nutzt und NumPy so nicht installieren kannst, dann schaue bitte in die [offizielle Dokumentation von Numpy.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## NumPy nutzen

Sobald wir NumPy installiert haben, können wir es als Library installieren:

In [1]:
import numpy as np

NumPy bietet viele eingebaute Funktionen und Möglichkeiten. Wir werden nicht alle davon abdecken, sondern eine Vorauswahl der höchst relevanten Aspekte von Numpy betrachten: Vektoren, Arrays, Matrizen und Zahlen Erzeugung. Wir beginnen mit den Arrays:

## NumPy Arrays

NumPy Arrays sind die Sache, die wir am häufigsten von NumPy nutzen werden. NumPy Arrays gibt es in zwei verschiedenen Arten: Vektoren und Matrizen. Vektoren sind immer eindimensionale Arrays und Matrizen sind zweidimensional (können allerdings auch nur eine Spalte oder eine Zeile haben).

Lass uns damit beginnen zu untersuchen, wie wir Arrays mit NumPy erstellen.

### Arrays erstellen

#### Aus einer Python Liste

Wir können Arrays erstellen, indem wir sie direkt aus einer Liste konvertieren.

In [2]:
meine_liste = [1,2,3]
meine_liste

[1, 2, 3]

In [3]:
np.array(meine_liste)

array([1, 2, 3])

In [4]:
meine_matrix = [[1,2,3],[4,5,6],[7,8,9]]
meine_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(meine_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Eingebaute Methoden

#### arange

Gibt gleichmäßig verteilte Werte innerhalb eines Intervalls zurück.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

#### zeros und ones

Erzeugt Arrays von Nullen oder Einsen

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### linspace

Gibt gleichmäßig verteilte Zahlen eines bestimmten Intervalls zurück.

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

#### eye

Erstellt eine Einheitsmatrix.

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random

NumPy kann außerdem auf viele verschiedene Weisen Zufallszahlen erzeugen.

#### rand

Erstellt ein Array der gegebenen Form und füllt es mit Zufallszahlen einer Gleichverteilung über [0,1].

In [15]:
np.random.rand(2)

array([0.81426586, 0.1356202 ])

In [16]:
np.random.rand(5,5)

array([[0.67793066, 0.34553848, 0.03806768, 0.4985321 , 0.28379202],
       [0.9231417 , 0.63016057, 0.16541753, 0.63967728, 0.06692652],
       [0.68644825, 0.60846287, 0.81655257, 0.75920966, 0.06826716],
       [0.12193555, 0.36659566, 0.43487767, 0.16803697, 0.85160051],
       [0.1491139 , 0.79168916, 0.96522461, 0.12684905, 0.9440541 ]])

#### randn

Gibt ein Sample (oder mehrere) einer "standard normal" Verteilung zurück. Anders als `rand`, dass gleichverteilt ist.

In [17]:
np.random.randn(2)

array([-1.56603011, -0.4117892 ])

In [18]:
np.random.randn(3,3)

array([[-1.47603882, -0.2062371 ,  1.58651633],
       [ 0.2431737 , -2.03372852,  0.61603461],
       [ 0.10008284,  1.37085135,  1.42237308]])

#### randint

Gibt Zufallszahlen von `low`(inklusive) bis `high`(exklusive) zurück.

In [19]:
np.random.randint(1,100)

13

In [20]:
np.random.randint(1,100,10)

array([92,  3, 37, 70, 17, 79, 17, 91, 18, 26])

### Array Attribute und Methoden

Wir werden jetzt einige nützliche Attribute und Methoden von Arrays betrachten:

In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([22, 21,  4, 17, 23, 14, 38,  7, 45, 36])

#### Reshape

Gibt ein Array zurück, das dieselben Daten in neuer Form enthält.

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### max, min, argmax, argmin

Diese Methoden sind nützlich, um Mindest- oder Höchstwerte zu finden. Oder dafür, deren Index zu finden.

In [25]:
ranarr

array([22, 21,  4, 17, 23, 14, 38,  7, 45, 36])

In [26]:
ranarr.max()

45

In [27]:
ranarr.argmax()

8

In [28]:
ranarr.min()

4

In [29]:
ranarr.argmin()

2

#### Shape

Shape ist eines der Attribute, die Arrays haben. Es ist keine Methode.

In [30]:
# Vektor
arr.shape

(25,)

In [31]:
# Achte auf die zwei Paare von Klammern
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [32]:
arr.reshape(1,25).shape

(1, 25)

In [33]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [34]:
arr.reshape(25,1).shape

(25, 1)

#### dtype

Du kannst außerdem den Datentyp des Objekts in einem Array feststellen:

In [35]:
arr.dtype

dtype('int32')

# Gut gemacht!